baseURL = "https://example.org/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
paginate = 2
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Simplicity - Hugo theme"
[author]
  gravatarEmail = "test@example.com"
  homepageText = "Simplicity"
  name = "Przemysław `eshlox` Kołodziejczyk"
[params]
  disqusShortname = "test"
  googleAnalytics = ""
  creativeCommonsLicence = "by-sa/4.0" # format: "short-name/version", set false to disable
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[[menu.pages]]
  name = "My projects"
  weight = -100
  identifier = "my-projects"
  url = "/my-projects/"
[[menu.pages]]
  name = "My photos"
  weight = -90
  identifier = "my-photos"
  url = "/my-photos/"
