baseURL: "https://example.org/"
languageCode: "en-us"
title: "Simplicity - Hugo theme"
theme: simplicity
paginate: 4
permalinks:
  posts: /:year/:month/:day/:slug/
pygmentsOptions:
  linenos: false
pygmentsStyle: native
pygmentsCodeFences: true
pygmentsUseClasses: true
disqusShortname: TEST
googleAnalytics: ""
enableEmoji: true
# relativeURLs: true
# canonifyURLs: true
author:
  twitter: eshlox
  facebook: eshlox
  github: eshlox
  telegram: eshlox
  gravatarEmail: test@example.com
  homepageText: ~/eshlox
