baseURL = "https://example.org/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
paginate = 2
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Simplicity - Hugo theme"
[author]
  gravatarEmail = "test@example.com"
  homepageText = "Simplicity"
  name = "Przemysław `eshlox` Kołodziejczyk"
[params]
  disqusShortname = "test"
  googleAnalytics = ""
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[[menu.pages]]
  name = "My projects"
  weight = -100
  identifier = "my-projects"
  url = "/my-projects/"
[[menu.pages]]
  name = "My photos"
  weight = -90
  identifier = "my-photos"
  url = "/my-photos/"
