baseURL = "https://example.org/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Simplicity - Hugo theme"
googleAnalytics = ""
enableRobotsTXT = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[imaging]
  resampleFilter = "box"
  quality = 75
  anchor = "smart"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[author]
  gravatarEmail = "test@example.com"
  homepageText = "Simplicity"
  name = "Przemysław `eshlox` Kołodziejczyk"
  telegram = "#"
  twitter = "#"
  github = "#"
  stackoverflow = "#"
  spotify = "#"
  google_plus = "#"
  linkedin = "#"
  messenger = "#"
  facebook = "#"
  rss = "/posts/index.xml"
  email = "#"
[params]
  description = "A blog about everything."
  disqusShortname = "test"
  licence = "[Some Rights Reserved](http://creativecommons.org/licenses/by-sa/4.0/)."
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
